# Generated by Django 5.2.7 on 2025-11-13 11:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Selling Price')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Paid')),
                ('amount_left', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Left')),
                ('date_last_paid', models.DateField(blank=True, null=True, verbose_name='Date Last Paid')),
                ('date_next_installment', models.DateField(blank=True, null=True, verbose_name='Next Installment Date')),
                ('status', models.CharField(choices=[('on-track', 'On Track'), ('due-soon', 'Due Soon'), ('overdue', 'Overdue'), ('fully-paid', 'Fully Paid')], default='on-track', max_length=20, verbose_name='Payment Status')),
                ('progress', models.IntegerField(default=0, help_text='Percentage of total amount paid', verbose_name='Payment Progress (%)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('naira_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('category', models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EcoSounder', 'EcoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], default='Receiver', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_number'], name='inventory_e_invoice_b97a60_idx'), models.Index(fields=['category'], name='inventory_e_categor_fbecb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_months', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('installment', 'Installment'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Import Invoice Number')),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Receiver', 'Receiver'), ('Accessory', 'Accessory'), ('Total Station', 'Total Station'), ('Level', 'Level'), ('Drones', 'Drones'), ('EcoSounder', 'EcoSounder'), ('Laser Scanner', 'Laser Scanner'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_enabled', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('serials', models.JSONField(blank=True, default=list)),
                ('available_serials', models.JSONField(blank=True, default=list)),
                ('sold_serials', models.JSONField(blank=True, default=list)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.equipmenttype', verbose_name='Equipment Type')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_tool_id', models.CharField(blank=True, max_length=100, null=True)),
                ('import_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Import Invoice Number')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tool')),
            ],
        ),
    ]
