# Generated by Django 5.2.7 on 2025-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='initial_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Initial Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Payment Months'),
        ),
    ]
