# Generated by Django 5.2.7 on 2026-02-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_codebatch_activationcode_codeassignmentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(default='not sold', max_length=50)),
                ('payment_status', models.CharField(default='not_applicable', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='inventory.codebatch')),
            ],
            options={
                'ordering': ['serial_number'],
                'unique_together': {('batch', 'serial_number')},
            },
        ),
    ]
