# Generated by Django 5.2.7 on 2026-02-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_batchserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationcode',
            name='duration',
        ),
    ]
