# Generated by Django 5.2.7 on 2026-02-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_activationcode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='qr_code_image',
            field=models.TextField(blank=True, help_text='Base64 encoded QR code image', null=True),
        ),
    ]
