# Generated by Django 5.2.7 on 2026-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_activationcode_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='pending_serials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
