# Generated by Django 5.2.7 on 2026-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_tool_pending_serials'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='equipment_type',
            field=models.CharField(blank=True, help_text='Base Only, Rover Only, Base & Rover Combo, etc.', max_length=100, null=True, verbose_name='Equipment Type'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='external_radio_serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External Radio Serial'),
        ),
    ]
