# Generated by Django 5.2.7 on 2026-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_saleitem_equipment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('installment', 'Installment'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
