# Generated by Django 5.2.7 on 2025-11-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_sale_import_invoice_saleitem_assigned_tool_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='import_invoice',
        ),
    ]
